### ISSUE TITLE
How do you make this faster?

### ISSUE THREAD

**Issue by jbeuckm** [StephanGeorg/staticmaps#44] opened 2020-07-23 16:54 UTC
We are generating some larger images ~800x800 and bogging down. In general, what would speed up the images?

**Comment by StephanGeorg** [comment] 2020-07-23 17:07
The slowest part is downloading the tiles. So if you could use a local tiles server, this would speed up the process.

- Where do you get the tiles from?
- Do you use 512px tiles?
- Is caching the tiles an option?

**Comment by StephanGeorg** [comment] 2020-09-11 09:03
Hi @jbeuckm 

Would be great to hear about your usecase and your experience with performance.

**Comment by JOGUI22** [comment] 2021-01-28 12:31
Hello, we are facing the same problem.

For 300x300 images is very fast, but for increasing size images 700x700 is worse, and for example 1080x1080 is much worse.

For example, for a 1080x1080 render (of 256x256 tiles) it downloads 25 tiles (we download all images in concurrency, 0.256seconds to get them all). The rendering part of these 25 tiles it lasts **5 full seconds**!

Any ideas? I'm debugging this module to find the issue.

We are using Node 10.23.1

**Comment by StephanGeorg** [comment] 2021-01-28 12:36
Could you please provide an example.

**Comment by JOGUI22** [comment] 2021-01-28 12:57
Hello @StephanGeorg , thank you for answering so fast.

I've been debugging, I've not finished but it does not seem a problem with the donwloading of times if it's all concurrent. It seems the problem is located at the moment the Sharp lib "composes" the image.

Here I attach a sample code that shows the problem. I've changed the tileUrl from one of ESRI that requires license to an open one to let you test it. I'm facing the same problem of time with both tileUrl sources.

```
//Init map
const options = {
    width: 1080,
    height: 1080,
    subdomains: ['a', 'b', 'c'],
    tileUrl: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    tileRequestLimit: 0,
    tileSize: 256
};
const map = new staticmapsLoader(options);

//Define polyline
const encodedPoly = "q~hkFp_|~UtEwOpAaJZkHO{E\\eBa@oAJaBnF{J_CuEx@mAh@wCu@gDRc@b@ADgBcBsDQyAd@eBkAcAUgBiGaKiAaDiG{Iu@AWsAiCi@uBcBcEVoCqDaAV_@rAe@Aa@YA_AoF_DkF_Hk@_@wB@}@]kDkEk@wA^eDpGcD?k@eA}AsC_@s@i@eBiDcBg@w@mAiBc@gAkCoDeAgAwAo@cGcCwGEyDhAmDCiFw@oC_DqCk@mA]wFmBkBDrGn@dD|B`FXbDw@fEsA`@gBMiIqDwDyBiEeHi@f@Q|CLpAt@hAq@e@Q^|@pGPMtBr@jB~Bv@|BJ~CnA~F`AhCdBoDt@c@NT`EpJpCzDIpFlBj@vBpBjAhDSR\\pB`BxB`C?`FxAb@|A|ArBjDbE~C`CjAlDA|Aa@b@eHg@aCn@lC~ChArDr@~FMtUWpC_CnFTfCUz@sE~@mAi@aE`AmAWoCVPlAfCvCVxCk@zAiDfCMz@~BJzIvBhB~AHhAjAvCzC`B|AjChH~G`Bv@dAnCp@f@n@W~CZe@jBjCbBpBxDfDhBnCdDdBbHhAg@rAmEt@U|@iBvAy@lCU"
const decodedPolyline = polylineUtils.decode(encodedPoly).map(point => {
    return [point[1], point[0]];
});
const polyline = {
    coords: decodedPolyline,
    color: '#FFA300',
    width: 4
};
map.addLine(polyline);

var renderhrstart = process.hrtime();

//Render the result
await map.render()

var renderhrend = process.hrtime(renderhrstart);
console.info("STATICMAP -> RENDER: Execution time (hr): %ds %dms", renderhrend[0], renderhrend[1] / 1000000);


return await map.image.buffer('image/jpeg');

```

Please ping me if you have any question. We can chat too.

**Comment by JOGUI22** [comment] 2021-01-28 14:35
Hello, I've opened a PR solving this issue. We will deploy this locally meanwhile we wait for this being merged. All tests passed. Ping me for questions.

**Closed** 2021-01-28 15:39 UTC

**Comment by StephanGeorg** [comment] 2021-01-28 15:45
@jbeuckm could you please test this also and confirm if this fixes your issues? Thanks.

**Comment by jbeuckm** [comment] 2022-05-05 20:50
> @jbeuckm could you please test this also and confirm if this fixes your issues? Thanks.

Sorry for the delay - looks good.
